// <auto-generated />
using System;
using Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistance.Migrations;

[DbContext(typeof(MixoLoggerDbContext))]
partial class MixoLoggerDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260915113525_Initiale";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.7.26381.103");

        modelBuilder.Entity("Infrastructure.Persistance.AliasDonnees", b =>
            {
                b.Property<string>("Alias")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<Guid>("IngredientId")
                    .HasColumnType("TEXT");

                b.HasKey("Alias");

                b.HasIndex("IngredientId");

                b.ToTable("AliasIngredients");
            });

        modelBuilder.Entity("Infrastructure.Persistance.BarDonnees", b =>
            {
                b.Property<Guid>("ProprietaireId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreeLe")
                    .HasColumnType("TEXT");

                b.Property<Guid>("Id")
                    .HasColumnType("TEXT");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER");

                b.HasKey("ProprietaireId");

                b.ToTable("Bars");
            });

        modelBuilder.Entity("Infrastructure.Persistance.CocktailDonnees", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid?>("AuteurId")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<string>("Nom")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("NomNormalise")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("AuteurId");

                b.HasIndex("NomNormalise")
                    .IsUnique();

                b.ToTable("Cocktails");
            });

        modelBuilder.Entity("Infrastructure.Persistance.ComposantDonnees", b =>
            {
                b.Property<Guid>("CocktailId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("IngredientId")
                    .HasColumnType("TEXT");

                b.Property<int>("Position")
                    .HasColumnType("INTEGER");

                b.Property<string>("Unite")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<double>("Valeur")
                    .HasColumnType("REAL");

                b.HasKey("CocktailId", "IngredientId");

                b.HasIndex("IngredientId");

                b.ToTable("CocktailIngredients");
            });

        modelBuilder.Entity("Infrastructure.Persistance.EtapeDonnees", b =>
            {
                b.Property<Guid>("CocktailId")
                    .HasColumnType("TEXT");

                b.Property<int>("Ordre")
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.HasKey("CocktailId", "Ordre");

                b.ToTable("EtapesRecette");
            });

        modelBuilder.Entity("Infrastructure.Persistance.IngredientDonnees", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreeLe")
                    .HasColumnType("TEXT");

                b.Property<string>("Nom")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("NomNormalise")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NomNormalise")
                    .IsUnique();

                b.ToTable("Ingredients");
            });

        modelBuilder.Entity("Infrastructure.Persistance.LigneStockDonnees", b =>
            {
                b.Property<Guid>("ProprietaireId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("IngredientId")
                    .HasColumnType("TEXT");

                b.Property<string>("Niveau")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<string>("VolumeUnite")
                    .HasMaxLength(5)
                    .HasColumnType("TEXT");

                b.Property<double?>("VolumeValeur")
                    .HasColumnType("REAL");

                b.HasKey("ProprietaireId", "IngredientId");

                b.HasIndex("IngredientId");

                b.ToTable("LignesStock");
            });

        modelBuilder.Entity("Infrastructure.Persistance.NoteDonnees", b =>
            {
                b.Property<Guid>("CocktailId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("UtilisateurId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("NoteeLe")
                    .HasColumnType("TEXT");

                b.Property<int>("Valeur")
                    .HasColumnType("INTEGER");

                b.HasKey("CocktailId", "UtilisateurId");

                b.ToTable("Notes");
            });

        modelBuilder.Entity("Infrastructure.Persistance.AliasDonnees", b =>
            {
                b.HasOne("Infrastructure.Persistance.IngredientDonnees", null)
                    .WithMany("Alias")
                    .HasForeignKey("IngredientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Infrastructure.Persistance.ComposantDonnees", b =>
            {
                b.HasOne("Infrastructure.Persistance.CocktailDonnees", null)
                    .WithMany("Composants")
                    .HasForeignKey("CocktailId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Infrastructure.Persistance.IngredientDonnees", "Ingredient")
                    .WithMany()
                    .HasForeignKey("IngredientId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Ingredient");
            });

        modelBuilder.Entity("Infrastructure.Persistance.EtapeDonnees", b =>
            {
                b.HasOne("Infrastructure.Persistance.CocktailDonnees", null)
                    .WithMany("Etapes")
                    .HasForeignKey("CocktailId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Infrastructure.Persistance.LigneStockDonnees", b =>
            {
                b.HasOne("Infrastructure.Persistance.IngredientDonnees", "Ingredient")
                    .WithMany()
                    .HasForeignKey("IngredientId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Infrastructure.Persistance.BarDonnees", null)
                    .WithMany("Lignes")
                    .HasForeignKey("ProprietaireId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Ingredient");
            });

        modelBuilder.Entity("Infrastructure.Persistance.NoteDonnees", b =>
            {
                b.HasOne("Infrastructure.Persistance.CocktailDonnees", null)
                    .WithMany()
                    .HasForeignKey("CocktailId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Infrastructure.Persistance.BarDonnees", b =>
            {
                b.Navigation("Lignes");
            });

        modelBuilder.Entity("Infrastructure.Persistance.CocktailDonnees", b =>
            {
                b.Navigation("Composants");

                b.Navigation("Etapes");
            });

        modelBuilder.Entity("Infrastructure.Persistance.IngredientDonnees", b =>
            {
                b.Navigation("Alias");
            });
#pragma warning restore 612, 618
    }
}
